image: astrabert/searchphi:latest

ports:
  - name: streamlit
    port: 8501
    onOpen: open-browser

tasks:
  - init: |
      docker run -d -p 8501:8501 astrabert/searchphi:latest
  - command: sleep 5000
