image: astrabert/searchphi:latest

ports:
  - name: streamlit
    port: 8501
    onOpen: open-browser

tasks:
  - init: |
      apt update && apt install git
  - command: streamlit run app.py
