networks:
  mynet:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - mynet
    environment:
      POSTGRES_DB: $pgql_db
      POSTGRES_USER: $pgql_user
      POSTGRES_PASSWORD: $pgql_psw
    volumes:
      - pgdata:/var/lib/postgresql/data

  semantic_memory:
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - mynet
    volumes:
      - "./qdrant_storage:/qdrant/storage"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mynet
  
  ui:
    build:
      context: ../chatbot-ui/
      dockerfile: Dockerfile.ui 
    ports:
      - "3000:3000"
    networks:
      - mynet

volumes:
    pgdata: